apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: smartcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ibrahimtalaat/dxc-frontend:latest
          ports:
            - containerPort: 8080
          env:  
            - name: MINIKUBE_IP
              valueFrom:
                configMapKeyRef:
                  name: app-config  
                  key: MINIKUBE_IP  
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config  
                  key: BACKEND_URL  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: smartcity
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort